#!/bin/zsh

CONFIG_FILE="$HOME/config/.duckdns"

if [[ -f $CONFIG_FILE ]]; then
  . $CONFIG_FILE
  echo url="https://www.duckdns.org/update?domains=$DOMAIN&token=$TOKEN&ip=$(tailscale ip)" | \
    curl -k -o - -K -
fi
