#!/bin/bash

CONFIG_FILE="$HOME/.duckdns"

if [[ -f $CONFIG_FILE ]]; then
  . $CONFIG_FILE
  echo url="https://www.duckdns.org/update?domains=$DOMAIN&token=$TOKEN&ip=$IP" | \
    curl -k -o $HOME/.duckdns.log -K -
fi
